package;

import yaml.Yaml;
import yaml.Parser;
import js.Browser;
import js.html.TextAreaElement;

class Main {
	static var textareaIn: TextAreaElement;
	static var textareaOut: TextAreaElement;

	static function main() {
		textareaIn = cast Browser.document.getElementById("in");
		textareaOut = cast Browser.document.getElementById("out");

		convertYaml(textareaIn.value);

		textareaIn.addEventListener('input', () -> {
			convertYaml(textareaIn.value);
		});
	}

	static function convertYaml(from: String) {
		try {
			final data: Scheme = Yaml.parse(from, Parser.options().useObjects());
			textareaOut.value = Scheme.generateGhosttyConfig(data);
			textareaIn.classList.remove("invalid");
		} catch (e) {
			trace(e);
			textareaIn.classList.add("invalid");
		}
	}
}

class Scheme {
	public var scheme: String;
	public var base00: String;
	public var base01: String;
	public var base02: String;
	public var base03: String;
	public var base04: String;
	public var base05: String;
	public var base06: String;
	public var base07: String;
	public var base08: String;
	public var base09: String;
	public var base0A: String;
	public var base0B: String;
	public var base0C: String;
	public var base0D: String;
	public var base0E: String;
	public var base0F: String;
	
	public static function generateGhosttyConfig(scheme: Scheme): String {
		return '# Scheme: ${scheme.scheme}
# Generated by Ghostty Base16 Converter
background = ${scheme.base00}
foreground = ${scheme.base05}
selection-background = ${scheme.base02}

palette = 0=#${scheme.base00}
palette = 1=#${scheme.base08}
palette = 2=#${scheme.base0B}
palette = 3=#${scheme.base0A}
palette = 4=#${scheme.base0D}
palette = 5=#${scheme.base0E}
palette = 6=#${scheme.base0C}
palette = 7=#${scheme.base05}
palette = 8=#${scheme.base03}
palette = 9=#${scheme.base08}
palette = 10=#${scheme.base0B}
palette = 11=#${scheme.base0A}
palette = 12=#${scheme.base0D}
palette = 13=#${scheme.base0E}
palette = 14=#${scheme.base0C}
palette = 15=#${scheme.base07}
palette = 16=#${scheme.base09}
palette = 17=#${scheme.base0F}
palette = 18=#${scheme.base01}
palette = 19=#${scheme.base02}
palette = 20=#${scheme.base04}
palette = 21=#${scheme.base06}';
	}
}
